# Generated by Django 5.1.3 on 2024-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("salud", "Salud"),
                    ("comercio", "Comercio"),
                    ("tecnologia", "Tecnología"),
                ],
                default="tecnologia",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="herramientas",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="imagen_principal",
            field=models.ImageField(blank=True, null=True, upload_to="proyectos/"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="url_github",
            field=models.URLField(blank=True, null=True),
        ),
    ]
